Userprofile
regilkent123/OJTPROJECT pull request #4
Opened 2018-05-22 04:07 UTC by regilkent123

2018-05-22 04:12 UTC, regilkent123 commented
naapil ang .pyc kuya pero ang .sqlite3 kay wala

2018-05-23 06:43 UTC, ozknightwalker requested changes

2018-05-23 06:43 UTC, ozknightwalker commented on userprofile/migrations/0003_auto_20180521_0055.py
> +class Migration(migrations.Migration):
please merge your migrations to 1

2018-05-23 06:43 UTC, ozknightwalker commented on userprofile/models.py
> +    trainee = 1
capitalize static variables please

2018-05-23 06:43 UTC, ozknightwalker commented on userprofile/models.py
> +    usertype = models.IntegerField(choices=utype, default=trainee)
use Positive Integer Field for this one

2018-05-23 06:43 UTC, ozknightwalker commented on userprofile/templates/userprofile/login.html
> +<link rel="stylesheet" type="text/css" href="{% static "userprofile/stylesheets/asd.css" %}" />
move this to another block

2018-05-23 06:43 UTC, ozknightwalker commented on userprofile/views.py
> +# unsay error? wait gi close lagi nimo ang forms
please remove this comments

2018-05-23 08:13 UTC, ozknightwalker requested changes

2018-05-23 08:13 UTC, ozknightwalker commented on userprofile/forms.py
> +            username = self.cleaned_data.get('username'),
remove spaces around `=`

2018-05-23 08:13 UTC, ozknightwalker commented on userprofile/templates/userprofile/loggedin.html
> +<p> Click <a href="{% url 'user:login' %}"> here </a> to log out.</p>
the link should logout user not login @regilkent123 @iamkatrinaanne

2018-05-23 08:13 UTC, ozknightwalker commented on userprofile/views.py
> +            auth_user = authenticate(username=username, password=password)
@regilkent123 @iamkatrinaanne what is the args for?

2018-05-23 08:37 UTC, ozknightwalker requested changes

2018-05-23 08:37 UTC, ozknightwalker commented on userprofile/views.py
> +        return render(request, self.template_name, {'form': form}, args)
@regilkent123 @iamkatrinaanne what is the `args` for? you already passed the forms back

2018-05-24 01:23 UTC, ozknightwalker approved these changes

2018-05-24 01:24 UTC, merged